repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy src/lightrace --no-error-summary
        language: system
        types: [python]
        pass_filenames: false
